# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github yihui/servr
  - ./travis-tool.sh install_github ropensci/RSelenium
  - ./travis-tool.sh install_github ropensci/gistr
  - ./travis-tool.sh install_github tdhock/ggplot2
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install shiny
- ./travis-tool.sh r_binary_install rmarkdown

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
