# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

r_binary_packages:
  - XML
  - shiny
  
r_packages:
  - gistr
  - RSelenium
  - rmarkdown

r_github_packages:
  - tdhock/ggplot2
  - yihui/servr

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    secure: "dgs1iD8l3NiPtFkDfYEsPCYyrQ/qehTm/oXqkB9ZvYph6pSUgzgb67yqwqH3sQqTae2xA4y6sqr+ekvTPnPonZtGZcSLEjEZqcZFN2Fg/YGeqKX91+oVRbLRtCO6/mPK35qrDQIui7ZMCfdufVSqWuG+3HizsauKXVUpsh1I1ek="
