# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

# Dependencies for running animint tests
r_binary_packages:
  - servr
  - XML
  - shiny
# Binary install of rmarkdown doesn't work (currently?)
r_github_packages:
  - tdhock/ggplot2
  - rstudio/rmarkdown
  - ropensci/RSelenium
  - ropensci/gistr

notifications:
  email:
    on_success: change
    on_failure: change
